#!/usr/bin/env python3
"""Generate Kismet ``apspoof=`` rules from Passive Vigilance's learned AP set.

Kismet's WIDS raises ``APSPOOF`` when a beacon or probe response claims an SSID
from a MAC that is not on that SSID's authorized list — but out of the box the
list is empty, so the impostor-SSID case never fires. PV already learns the
legitimate BSSID↔SSID set at a location (the ``beacon_evidence`` table in
``entities.db``), which is exactly the ground truth Kismet is missing
(docs/design-ap-identity-evil-twin.md §III.2). This tool turns that table into
an ``apspoof=`` config fragment the operator appends to
``/etc/kismet/kismet_site.conf`` (then restarts Kismet).

Usage
-----
  # Print the fragment for review
  python3 scripts/generate_apspoof.py

  # Write it to a file
  python3 scripts/generate_apspoof.py --output data/apspoof_baseline.conf

  # Require an AP to have beaconed more before it is trusted
  python3 scripts/generate_apspoof.py --min-beacons 100

Notes
-----
- A legitimately added AP (new mesh node, replaced router) is a *baseline
  update*: re-run this tool and refresh the fragment, don't ignore the alert
  forever.
- SSIDs whose BSSID set legitimately churns (Wi-Fi Direct's ``DIRECT-…``) are
  excluded by default — an allowlist for them would just manufacture APSPOOF
  noise. Override with ``--include-prefix``.
- The database is opened read-only; safe to run against a live node.
"""

import argparse
import os
import re
import sqlite3
import sys
from datetime import datetime, timezone

# SSID prefixes whose legitimate BSSID set churns (soft APs spun up on demand
# with fresh MACs) — allowlisting them guarantees future false APSPOOF fires.
_DEFAULT_EXCLUDE_PREFIXES = ("DIRECT-",)


def _rule_name(index: int) -> str:
    """A unique, syntax-safe rule name (Kismet wants one per apspoof line)."""
    return f"pvbase{index}"


def _ssid_regex(ssid: str) -> str:
    """Anchored, escaped regex matching exactly this SSID.

    The shipped ``kismet_alerts.conf`` examples show the ``ssid=`` value is
    compiled as a regex (``ssid="(?i:foobar)"``), so an SSID containing regex
    metacharacters must be escaped, and anchoring prevents substring matches.
    """
    return "^" + re.escape(ssid) + "$"


def generate_rules(db_path: str, *, min_beacons: int = 10,
                   exclude_prefixes: tuple = _DEFAULT_EXCLUDE_PREFIXES) -> list:
    """Build the ``apspoof=`` lines from beacon_evidence.

    One rule per SSID, listing every BSSID that has beaconed it at least
    *min_beacons* times (a one-beacon wonder is not evidence the AP belongs
    here). Returns the lines without trailing newlines.
    """
    uri = f"file:{db_path}?mode=ro"
    conn = sqlite3.connect(uri, uri=True)
    try:
        rows = conn.execute(
            "SELECT ssid, bssid FROM beacon_evidence "
            "WHERE ssid != '' AND beacon_count >= ? "
            "ORDER BY ssid, bssid",
            (min_beacons,),
        ).fetchall()
    finally:
        conn.close()

    by_ssid: dict = {}
    for ssid, bssid in rows:
        if any(ssid.startswith(p) for p in exclude_prefixes):
            continue
        by_ssid.setdefault(ssid, []).append(bssid)

    lines = []
    for index, (ssid, bssids) in enumerate(sorted(by_ssid.items())):
        macs = ",".join(b.upper() for b in bssids)
        lines.append(
            f'apspoof={_rule_name(index)}:ssid="{_ssid_regex(ssid)}",validmacs="{macs}"'
        )
    return lines


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate Kismet apspoof= rules from PV's learned AP set")
    parser.add_argument(
        "--db", default=os.getenv("ENTITY_DB_PATH", "data/entities.db"),
        help="Path to entities.db (default: ENTITY_DB_PATH or data/entities.db)")
    parser.add_argument(
        "--min-beacons", type=int, default=10,
        help="Minimum beacon_count before a BSSID is trusted for its SSID (default 10)")
    parser.add_argument(
        "--include-prefix", action="append", default=[],
        help="SSID prefix to include despite the default exclusions (repeatable)")
    parser.add_argument(
        "--output", default=None,
        help="Write the fragment to this file (default: print to stdout)")
    args = parser.parse_args(argv)

    if not os.path.exists(args.db):
        parser.error(f"database not found: {args.db}")

    exclude = tuple(p for p in _DEFAULT_EXCLUDE_PREFIXES
                    if p not in args.include_prefix)
    lines = generate_rules(args.db, min_beacons=args.min_beacons,
                           exclude_prefixes=exclude)

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = [
        "# Kismet APSPOOF allowlist — generated by Passive Vigilance",
        f"# scripts/generate_apspoof.py on {stamp} from {args.db}",
        f"# {len(lines)} trusted SSID(s). Append to /etc/kismet/kismet_site.conf",
        "# and restart Kismet. Re-generate after a legitimate AP change.",
    ]
    fragment = "\n".join(header + lines) + "\n"

    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(fragment)
        sys.stderr.write(f"Wrote {len(lines)} apspoof rule(s) to {args.output}\n")
    else:
        sys.stdout.write(fragment)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
